### ISSUE TITLE
10 Best SEO tools your project needs in 2022

### ISSUE THREAD

**Issue by RainboeStrykr** [genicsblog/genicsblog.com#86]
### Idea
SEO tools play a significant role in increasing organic traffic, maintaining and improving Ranking, and providing the right or target keywords. Nowadays, there are many SEO tools available, whether paid or free. We have discussed the 10 best SEO tools in 2022, which will help you in many ways like gaining organic traffic etc. And see which works best for you.

### Topics

**Category**: seo

**Tags**: beginners. tools

### Cross-posting?

No

**Comment by gouravkhunger** [comment]
That would be a great addition to the existing 4 tools posted [here](https://genicsblog.com/must-have-free-seo-tools-for-everyone)!

**Comment by RainboeStrykr** [comment]
Sure, so I shall begin the draft for it?

**Comment by gouravkhunger** [comment]
Yup, sure!

**Comment by gouravkhunger** [comment]
Do change the name of the fork from `genicsblog.github.io` to `genicsblog.com` as there were changes in automerge draft check. Maybe also pull the latest commits so your fork is upto date 😄

**Comment by RainboeStrykr** [comment]
https://github.com/genicsblog/genicsblog.com/pull/87

I'm done with the draft @gouravkhunger

**Comment by gouravkhunger** [comment]
Thanks for the article :)
I read it and got to know about a lot more tools which I didn't even know of! Overall, the content is really nice.

I think a few amendments would make the article even better:
- Adding images for the tools for two reasons: Showcasing the tool, which will also increase average reading time for the article.
- Adding Links to the platforms for easy access.
- Using normal text numbering instead of emojis for headings because it looks kind of odd I guess. Within the article they're fine!
- Adding a bit of space within the paragraphs because, on mobile devices, the text seems a bit conjusted. Spacing helps the users to read efficiently :)

I'll ask the team to do most of the things, but could you take screenshots of the websites?

This is a [great tool to take screenshots](https://pika.rishimohan.me/) without having to download the images (saves time), you can copy them to the clipboard and send the images here in the comments by pasting the image. I'll add them to the article and we'll publish it by tomorrow!

**Comment by RainboeStrykr** [comment]
Thank you Gourav! Sure, you can go ahead with the amendments.

![Imgur](https://i.imgur.com/NkDBflj.png)
![Imgur](https://i.imgur.com/XgjGa7s.png)
![Imgur](https://i.imgur.com/NyHhHGg.png)
![Imgur](https://i.imgur.com/PZ2Mf4q.png)
![Imgur](https://i.imgur.com/PD98LRY.png)
![Imgur](https://i.imgur.com/zFo3rlA.png)
![Imgur](https://i.imgur.com/HHm6ead.png)
![Imgur](https://i.imgur.com/658DJMZ.png)
![Imgur](https://i.imgur.com/AC34l4R.png)
![Imgur](https://i.imgur.com/R1X2x6a.png)

Here are all of the screenshots @gouravkhunger

**Comment by gouravkhunger** [comment]
This is great, thank you!

**Comment by gouravkhunger** [comment]
I've published [the post](https://genicsblog.com/10-seo-tools-you-need-to-use-in-2022) 🎉
